services:
  redis:
    image: redis:7-alpine
    container_name: redis-server
    ports:
      - "6379:6379"
    restart: unless-stopped

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    container_name: fastapi-app
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - GROQ_API_KEY=${GROQ_API_KEY}
    depends_on:
      - redis
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped

  react:
    build:
      context: ./my-react-app      
      dockerfile: Dockerfile.react
    container_name: react-frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true 
    restart: unless-stopped